web/router.ex
defmodule Officetournament.Router do
  use Officetournament.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Officetournament do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index
    get "/login/", UserSessionController, :index
    post "/login/", UserSessionController, :login
    get "/logout/", UserSessionController, :logout
    resources "/leagues", LeagueController
    post "/leagues/:id/join", LeagueController, :join
    resources "/games", GameController
  end

  scope "/admin", as: :admin do
    pipe_through :browser # Use the default browser stack

    resources "/users", Officetournament.Admin.UserController
    resources "/leagues", Officetournament.Admin.LeagueController
  end

  scope "/auth", Officetournament do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Officetournament do
  #   pipe_through :api
  # end

  # https://github.com/rrrene/elixirstatus-web/blob/07ca31cd035e67666a598589b7f4490846dfc9d8/web/router.ex
  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
    user_id = get_session(conn, :current_user_id)
    assign(conn, :current_user, Officetournament.UserSessionController.find_by_id(user_id))
  end
end

web/views/layout_view.ex
defmodule Officetournament.LayoutView do
  use Officetournament.Web, :view
end

web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Office Tournament</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin.css") %>">
  </head>

  <body>

    <nav class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="<%= home_path @conn, :index %>">
              <img src="/images/office-ladder-logo.svg" />
            </a></li>
            <li "<%= "/" |> active(@conn) |> raw %>"><a href="<%= home_path @conn, :index %>">Home</a></li>
            <li "<%= "/users" |> active(@conn) |> raw %>"><a href="<%= admin_user_path @conn, :index %>">Users</a></li>
            <li "<%= "/leagues" |> active(@conn) |> raw %>"><a href="<%= admin_league_path @conn, :index %>">Leagues</a></li>
            <li "<%= "/logout" |> active(@conn) |> raw %>"><a href="<%= user_session_path @conn, :logout %>">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Office Tournament</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" media="all">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <link href='//fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <link href='//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' rel='stylesheet' type='text/css'>
</head>
<body>
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
  <%= render @view_module, @view_template, assigns %>
  <div class="footer"></div>

  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>

web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Office Tournament</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" media="all">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <link href='//fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <link href='//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' rel='stylesheet' type='text/css'>
</head>
<body>
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
  <%= render @view_module, @view_template, assigns %>
  <div class="footer"></div>

  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>